###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7.20
      container_name: exactaworks-api-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123.456
        - MYSQL_DATABASE=test_backend_exactaworks
        - MYSQL_USER=exactaworks
        - MYSQL_PASSWORD=123mudar
      ports:
        - "3322:3306"
      networks:
        - exactaworks-dev-network

    webserver:
      image: nginx:alpine
      container_name: exactaworks-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9000:80"
      networks:
        - exactaworks-dev-network

    php-fpm:
      build: phpdocker/php-fpm
      container_name: exactaworks-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        - exactaworks-dev-network

networks:
    exactaworks-dev-network:
        driver: bridge



